### ISSUE TITLE
RE: EU site is not supported in API library

### ISSUE THREAD

**Issue by nitikeshd** [urbanairship/connect-python-library#6]
**All bugs, feature requests, implementation concerns or general queries should be sent to our [support team](https://support.airship.com/).**

You are welcome to submit an issue here for bugs, but please also reach out to our support team as well.

Before completing the form below, please check the following:

- [ √] You are using the most recent version of the library. 
- [ √] You are using a supported version of Python for that library version. 
- [ √] This issue is reproducible. 

## Expected Behavior
It should give us event tracking informations with filter.

## Current Behavior
API libraries is not supporting EU sites and in API we are getting blank response.
![image](https://user-images.githubusercontent.com/32154791/146602473-b90192c7-2ee0-4c38-b39f-cb91224dc4c1.png)

## Possible Solution
Enable EU site base urls.

## Steps to Reproduce
NOTE: Basic authentication is working with it. But in doc its writtebn to use bearer token which was too much confusing for us.
1. Use Basic authentication in postman and API library and tried with location param.
2. code: consumer = uaconnect.Consumer(app_key, access_token, location="eu", uaconnect.FileRecorder('.offset'))
3. But location does not exists. So, base url its taking is the other one.
4. And in postman i am getting blank response as well

So, its a blocker for our development.

We are trying to get event tracking insights using filters. Please help us out in this.

**Comment by nitikeshd** [comment]
Apart from that, we are doing the same changes in PHP as well. So, we need that enabled in php library also.

**Comment by nitikeshd** [comment]
is there any update in this one?

**Comment by pdxmele** [comment]
Hi, we have a ticket for this but don't expect to get to it super quickly. We're happy to look at any pull requests though!

With PHP, we are planning to replace the PHP library with an auto-build from our API docs, so please keep an eye out for that.

**Comment by aschuman0** [comment]
@nitikeshd - in taking a look at this, it appears that you can pass `url` as a parameter to the `uaconnect.Consumer` class.

example:
```
consumer = uaconnect.Consumer(app_key="my_app_key", access_token="my_token", url="https://connect.asnapieu.com/api/events/" ...)
```

That should get you going. Please let us know if you encounter any more issues.

**Comment by nitikeshd** [comment]
can you please share the code for php as well?

**Comment by aschuman0** [comment]
@nitikeshd - it does not seem that is possible with the php channels library at this time. Please open an issue on that repository and we will have someone take a look, though I cannot promise an ETA. As always, PRs are encouraged.
